# when installing on Ubuntu, execute the following in bash terminal before installing tidyverse and ggraph
#sudo apt-get install libxml2-dev libssl-dev libcurl4-openssl-dev libudunits2-dev 

install.packages("ggpubr")
install.packages("tidyverse")
install.packages("ggraph")
install.packages("igraph")
install.packages("corrplot")
install.packages("gplots")
install.packages("Hmisc")
install.packages("FactoMineR")
install.packages("ica")
install.packages("Rtsne")
install.packages("RColorBrewer")
install.packages("multcomp")
install.packages("ggplot2")
install.packages("R.matlab")
install.packages("colorRamps")
install.packages("GGally")
install.packages("rowr")
install.packages("missMDA")
install.packages("rlist")
install.packages("DescTools")
install.packages("data.table")
#install.packages("qgraph") # ERROR: dependencies ‘psych’, ‘lavaan’ are not available for package ‘qgraph’
install.packages("dplyr")
install.packages("pbapply")
install.packages("rowr")
install.packages("NBR")
install.packages("remotes")
remotes::install_github("phively/wranglR")
install.packages("mgcViz")
install.packages("easypackages")
install.packages("lmerTest")
install.packages("RhpcBLASctl")

