# when installing on Ubuntu, execute the following in bash terminal before installing tidyverse and ggraph
#sudo apt-get install libxml2-dev libssl-dev libcurl4-openssl-dev libudunits2-dev 


install.packages("ggpubr",type="source")
install.packages("tidyverse",type="source")
install.packages("ggraph",type="source")
install.packages("igraph",type="source")
install.packages("corrplot",type="source")
install.packages("gplots",type="source")
install.packages("Hmisc",type="source")
install.packages("FactoMineR",type="source")
install.packages("ica",type="source")
install.packages("Rtsne",type="source")
install.packages("RColorBrewer",type="source")
install.packages("multcomp",type="source")
install.packages("ggplot2",type="source")
install.packages("R.matlab",type="source")
install.packages("colorRamps",type="source")
install.packages("GGally",type="source")
install.packages("rowr",type="source")
install.packages("missMDA",type="source")
install.packages("rlist",type="source")
install.packages("DescTools",type="source")
install.packages("data.table",type="source")
#install.packages("qgraph",type="source") # ERROR: dependencies ‘psych’, ‘lavaan’ are not available for package ‘qgraph’
install.packages("dplyr",type="source")
install.packages("pbapply",type="source")
install.packages("rowr",type="source")
install.packages("NBR",type="source")
install.packages("remotes",type="source")
remotes::install_github("phively/wranglR")
install.packages("mgcViz",type="source")
install.packages("easypackages",type="source")
install.packages("lmerTest",type="source")
install.packages("RhpcBLASctl")

