%-----------------------------------------------------------------------
% Job saved on 14-Jan-2019 00:37:19 by cfg_util (rev $Rev: 6942 $)
% spm SPM - SPM12 (7219)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.stats.factorial_design.dir = '<UNDEFINED>';
matlabbatch{1}.spm.stats.factorial_design.des.anova.icell(1).scans = '<UNDEFINED>';
matlabbatch{1}.spm.stats.factorial_design.des.anova.icell(2).scans = '<UNDEFINED>';
matlabbatch{1}.spm.stats.factorial_design.des.anova.icell(3).scans = '<UNDEFINED>';
matlabbatch{1}.spm.stats.factorial_design.des.anova.icell(4).scans = '<UNDEFINED>';
matlabbatch{1}.spm.stats.factorial_design.des.anova.dept = 0;
matlabbatch{1}.spm.stats.factorial_design.des.anova.variance = 1;
matlabbatch{1}.spm.stats.factorial_design.des.anova.gmsca = 0;
matlabbatch{1}.spm.stats.factorial_design.des.anova.ancova = 0;
%%
matlabbatch{1}.spm.stats.factorial_design.cov(1).c = [2
                                                      2
                                                      2
                                                      1
                                                      2
                                                      2
                                                      1
                                                      1
                                                      2
                                                      2
                                                      2
                                                      2
                                                      1
                                                      1
                                                      2
                                                      2
                                                      2
                                                      1
                                                      1
                                                      2
                                                      2
                                                      2
                                                      2
                                                      1
                                                      1
                                                      2
                                                      1
                                                      2
                                                      1
                                                      2
                                                      1
                                                      2
                                                      2
                                                      1
                                                      1
                                                      2
                                                      2
                                                      2
                                                      2
                                                      1
                                                      2
                                                      1
                                                      2
                                                      1
                                                      2
                                                      2
                                                      2
                                                      1
                                                      1
                                                      2
                                                      1
                                                      2
                                                      2
                                                      2
                                                      2
                                                      1
                                                      2
                                                      2
                                                      1
                                                      1
                                                      1
                                                      2
                                                      2
                                                      2
                                                      2
                                                      1
                                                      1
                                                      1
                                                      2
                                                      1
                                                      2
                                                      1
                                                      1
                                                      1
                                                      2
                                                      1
                                                      1
                                                      2
                                                      2
                                                      2
                                                      2
                                                      2
                                                      1
                                                      2
                                                      1
                                                      2
                                                      1
                                                      2
                                                      2
                                                      1
                                                      1
                                                      2
                                                      1
                                                      1
                                                      1
                                                      2
                                                      2
                                                      2
                                                      1
                                                      1
                                                      1
                                                      1
                                                      1
                                                      1
                                                      2
                                                      1
                                                      2
                                                      1
                                                      2
                                                      2
                                                      1
                                                      1
                                                      2
                                                      2
                                                      1
                                                      1
                                                      1
                                                      2
                                                      1
                                                      1
                                                      1
                                                      1
                                                      1
                                                      1
                                                      2
                                                      1
                                                      2
                                                      2
                                                      1
                                                      1
                                                      1
                                                      1
                                                      2
                                                      2
                                                      1
                                                      1
                                                      2
                                                      1
                                                      1
                                                      2
                                                      1
                                                      2
                                                      1
                                                      1
                                                      2
                                                      2
                                                      2
                                                      1
                                                      1
                                                      1
                                                      1
                                                      2
                                                      1
                                                      2
                                                      1
                                                      2
                                                      2
                                                      1
                                                      2
                                                      1
                                                      1
                                                      2
                                                      2
                                                      1
                                                      1];
%%
matlabbatch{1}.spm.stats.factorial_design.cov(1).cname = 'Sex';
matlabbatch{1}.spm.stats.factorial_design.cov(1).iCFI = 1;
matlabbatch{1}.spm.stats.factorial_design.cov(1).iCC = 5;
%%
matlabbatch{1}.spm.stats.factorial_design.cov(2).c = [3967
                                                      4170
                                                      4175
                                                      4126
                                                      4210
                                                      4277
                                                      3885
                                                      4329
                                                      4056
                                                      4262
                                                      4000
                                                      4115
                                                      3996
                                                      4231
                                                      4132
                                                      4292
                                                      4105
                                                      4096
                                                      4080
                                                      3943
                                                      4010
                                                      4207
                                                      4177
                                                      4140
                                                      4519
                                                      4028
                                                      4187
                                                      4258
                                                      4790
                                                      4701
                                                      4849
                                                      4654
                                                      4755
                                                      4782
                                                      4792
                                                      4073
                                                      3982
                                                      4170
                                                      4187
                                                      4141
                                                      4205
                                                      4066
                                                      4159
                                                      4129
                                                      4276
                                                      3890
                                                      4044
                                                      3979
                                                      3983
                                                      4146
                                                      4371
                                                      4055
                                                      4214
                                                      4168
                                                      4008
                                                      4183
                                                      4168
                                                      4269
                                                      4118
                                                      3971
                                                      4024
                                                      4132
                                                      3903
                                                      3997
                                                      4008
                                                      4160
                                                      4109
                                                      4113
                                                      4260
                                                      4183
                                                      4160
                                                      4143
                                                      4063
                                                      4133
                                                      4585
                                                      4690
                                                      4626
                                                      4224
                                                      4710
                                                      4441
                                                      4650
                                                      4781
                                                      4649
                                                      4734
                                                      4776
                                                      4860
                                                      4089
                                                      4195
                                                      4179
                                                      4017
                                                      4121
                                                      4293
                                                      4036
                                                      4112
                                                      4263
                                                      4228
                                                      4121
                                                      4010
                                                      4012
                                                      4085
                                                      4223
                                                      4111
                                                      4083
                                                      4654
                                                      4677
                                                      4693
                                                      4797
                                                      4205
                                                      4036
                                                      4045
                                                      4098
                                                      4227
                                                      4132
                                                      4202
                                                      3925
                                                      4332
                                                      4081
                                                      4077
                                                      4467
                                                      4320
                                                      3999
                                                      4003
                                                      4157
                                                      4164
                                                      4043
                                                      4137
                                                      4117
                                                      4218
                                                      4127
                                                      4238
                                                      4289
                                                      4128
                                                      4087
                                                      4015
                                                      3857
                                                      3959
                                                      4042
                                                      4134
                                                      4010
                                                      4044
                                                      3999
                                                      4023
                                                      4135
                                                      4111
                                                      4157
                                                      4207
                                                      4140
                                                      4147
                                                      4187
                                                      4764
                                                      4127
                                                      4282
                                                      4668
                                                      4730
                                                      4671
                                                      4724
                                                      4182
                                                      4668
                                                      4735
                                                      4652
                                                      4632
                                                      4795
                                                      4669
                                                      4793
                                                      4863];
%%
matlabbatch{1}.spm.stats.factorial_design.cov(2).cname = 'Age';
matlabbatch{1}.spm.stats.factorial_design.cov(2).iCFI = 1;
matlabbatch{1}.spm.stats.factorial_design.cov(2).iCC = 1;
%%
matlabbatch{1}.spm.stats.factorial_design.cov(3).c = [4
                                                      5
                                                      5
                                                      4
                                                      5
                                                      5
                                                      5
                                                      4
                                                      5
                                                      6
                                                      1
                                                      4
                                                      4
                                                      5
                                                      5
                                                      3
                                                      6
                                                      6
                                                      6
                                                      2
                                                      4
                                                      4
                                                      3
                                                      4
                                                      3
                                                      5
                                                      3
                                                      6
                                                      4
                                                      3
                                                      3
                                                      3
                                                      3
                                                      3
                                                      6
                                                      5
                                                      6
                                                      5
                                                      5
                                                      3
                                                      6
                                                      5
                                                      6
                                                      4
                                                      5
                                                      2
                                                      5
                                                      4
                                                      3
                                                      6
                                                      5
                                                      4
                                                      5
                                                      5
                                                      3
                                                      4
                                                      4
                                                      3
                                                      2
                                                      3
                                                      6
                                                      4
                                                      3
                                                      3
                                                      4
                                                      4
                                                      6
                                                      5
                                                      6
                                                      6
                                                      6
                                                      5
                                                      3
                                                      3
                                                      6
                                                      5
                                                      2
                                                      3
                                                      2
                                                      6
                                                      5
                                                      4
                                                      3
                                                      3
                                                      2
                                                      6
                                                      3
                                                      5
                                                      4
                                                      1
                                                      6
                                                      6
                                                      4
                                                      6
                                                      3
                                                      5
                                                      4
                                                      2
                                                      2
                                                      3
                                                      3
                                                      3
                                                      3
                                                      2
                                                      4
                                                      4
                                                      4
                                                      6
                                                      3
                                                      5
                                                      6
                                                      4
                                                      6
                                                      6
                                                      2
                                                      6
                                                      6
                                                      5
                                                      4
                                                      4
                                                      6
                                                      4
                                                      4
                                                      6
                                                      4
                                                      6
                                                      6
                                                      4
                                                      3
                                                      4
                                                      6
                                                      4
                                                      5
                                                      5
                                                      4
                                                      3
                                                      2
                                                      6
                                                      3
                                                      5
                                                      4
                                                      4
                                                      4
                                                      1
                                                      3
                                                      3
                                                      3
                                                      6
                                                      5
                                                      6
                                                      6
                                                      3
                                                      6
                                                      6
                                                      4
                                                      4
                                                      3
                                                      5
                                                      4
                                                      3
                                                      5
                                                      5
                                                      6
                                                      3
                                                      6];
%%
matlabbatch{1}.spm.stats.factorial_design.cov(3).cname = 'SES';
matlabbatch{1}.spm.stats.factorial_design.cov(3).iCFI = 1;
matlabbatch{1}.spm.stats.factorial_design.cov(3).iCC = 1;
%%
matlabbatch{1}.spm.stats.factorial_design.cov(4).c = [39.5
                                                      41.5
                                                      46.5
                                                      48
                                                      44.5
                                                      46.5
                                                      43.5
                                                      47
                                                      44.5
                                                      48.5
                                                      39.5
                                                      48
                                                      42
                                                      47.5
                                                      40
                                                      36.5
                                                      46.5
                                                      46.5
                                                      48.5
                                                      55
                                                      43.5
                                                      36.5
                                                      41.5
                                                      39.5
                                                      44
                                                      47.5
                                                      46
                                                      46
                                                      42
                                                      48
                                                      45
                                                      45
                                                      50
                                                      41.5
                                                      41
                                                      43
                                                      35
                                                      39.5
                                                      45
                                                      41.5
                                                      34
                                                      45
                                                      40.5
                                                      41.5
                                                      41
                                                      31.5
                                                      39.5
                                                      47
                                                      38.5
                                                      43
                                                      35.5
                                                      37.5
                                                      41.5
                                                      44
                                                      40
                                                      35.5
                                                      45
                                                      34
                                                      42.5
                                                      41
                                                      38
                                                      45.5
                                                      41
                                                      43.5
                                                      47.5
                                                      40
                                                      40.5
                                                      46
                                                      41
                                                      39
                                                      45
                                                      41
                                                      37.5
                                                      46
                                                      42.5
                                                      39
                                                      36.5
                                                      50
                                                      35.5
                                                      46
                                                      40.5
                                                      33
                                                      37.5
                                                      39.5
                                                      29
                                                      43.5
                                                      41
                                                      39.5
                                                      42.5
                                                      42.5
                                                      45
                                                      42
                                                      31
                                                      35
                                                      47.5
                                                      45
                                                      48
                                                      50.5
                                                      41.5
                                                      39
                                                      43
                                                      41.5
                                                      45
                                                      41
                                                      45.5
                                                      40.5
                                                      40
                                                      39
                                                      34.5
                                                      42.5
                                                      45.5
                                                      47
                                                      43.5
                                                      42
                                                      43
                                                      43.5
                                                      51.5
                                                      47.5
                                                      37.5
                                                      38.5
                                                      42.5
                                                      44.5
                                                      47
                                                      48
                                                      48.5
                                                      39
                                                      47
                                                      46.5
                                                      41
                                                      51
                                                      42.5
                                                      42.5
                                                      38.5
                                                      39
                                                      41.5
                                                      51
                                                      46.5
                                                      47
                                                      47
                                                      41
                                                      40
                                                      46.5
                                                      47.5
                                                      41
                                                      43.5
                                                      54.5
                                                      37.5
                                                      44
                                                      52
                                                      47.5
                                                      43.5
                                                      39.5
                                                      44
                                                      42
                                                      43
                                                      45
                                                      45
                                                      43.5
                                                      48.5
                                                      49
                                                      54
                                                      41
                                                      48
                                                      42.5
                                                      44.5];
%%
matlabbatch{1}.spm.stats.factorial_design.cov(4).cname = 'Parental_Age';
matlabbatch{1}.spm.stats.factorial_design.cov(4).iCFI = 1;
matlabbatch{1}.spm.stats.factorial_design.cov(4).iCC = 1;
matlabbatch{1}.spm.stats.factorial_design.multi_cov = struct('files', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.im = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.em = {''};
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm = 1;
matlabbatch{2}.spm.stats.fmri_est.spmmat(1) = cfg_dep('Factorial design specification: SPM.mat File', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{2}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;
matlabbatch{3}.spm.stats.con.spmmat(1) = cfg_dep('Model estimation: SPM.mat File', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{3}.spm.stats.con.consess{1}.fcon.name = 'Effect of Sibling status';
matlabbatch{3}.spm.stats.con.consess{1}.fcon.weights = [-1 1 0 0 0 0 0 0
                                                        0 -1 1 0 0 0 0 0
                                                        0 0 -1 1 0 0 0 0];
matlabbatch{3}.spm.stats.con.consess{1}.fcon.sessrep = 'none';
matlabbatch{3}.spm.stats.con.delete = 0;
matlabbatch{4}.spm.stats.results.spmmat(1) = cfg_dep('Contrast Manager: SPM.mat File', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{4}.spm.stats.results.conspec.titlestr = '';
matlabbatch{4}.spm.stats.results.conspec.contrasts = 1;
matlabbatch{4}.spm.stats.results.conspec.threshdesc = 'none';
matlabbatch{4}.spm.stats.results.conspec.thresh = 0.00025;
matlabbatch{4}.spm.stats.results.conspec.extent = 0;
matlabbatch{4}.spm.stats.results.conspec.conjunction = 1;
matlabbatch{4}.spm.stats.results.conspec.mask.none = 1;
matlabbatch{4}.spm.stats.results.units = 1;
matlabbatch{4}.spm.stats.results.export{1}.ps = true;
matlabbatch{4}.spm.stats.results.export{2}.fig = true;
