---
title: "test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```




```{r data, echo=TRUE}
knitr::opts_chunk$set(include = FALSE)

#parent_dir <- "D:/atiroms"
parent_dir <- "C:/Users/atiro"

script_dir <- file.path(parent_dir,"GitHub/MRI_Analysis")
input_dir <- file.path(parent_dir,"DropBox/MRI/Statistics/TS_Clinical")
output_dir <- file.path(input_dir,"Clinical_data")

subject_subset <- data.frame(W1_T1QC=1)


#library(ggplot2)
#library(ggpubr)
#library(plyr)

clinical_data$Sex<-factor(clinical_data$Sex, levels=c(1,2))
clinical_data <-clinical_data[which(!is.na(clinical_data$Sex)),]
TS_data<-clinical_data[which(!is.na(clinical_data$W1_Tanner_Stage)),]

```

```{r plot, echo=FALSE}
ggplot(as.data.frame(with(TS_data, table(W1_Tanner_Stage = factor(W1_Tanner_Stage), Sex))),aes(factor(W1_Tanner_Stage), y = Freq, fill = Sex)) +
  geom_col(width=0.7, position = position_dodge(width=0.8)) + 
  scale_fill_manual(name=NULL,labels=c("Male","Female"),values=c("steelblue2","lightcoral"),drop=FALSE) +
  ggtitle("Tanner Stage for pn-TTC 1st Wave") +
  xlab("Tanner Stage") +
  ylab("Number of Subjects") +
  theme_light()+
  theme(plot.title = element_text(hjust = 0.5),legend.justification=c(1,1), legend.position=c(0.9,0.9),panel.grid.major.x=element_blank())
```


