%-----------------------------------------------------------------------
% Job saved on 11-Jun-2019 09:14:56 by cfg_util (rev $Rev: 6942 $)
% spm SPM - SPM12 (7219)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
%%
matlabbatch{1}.spm.spatial.preproc.channel.vols = {
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00001_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00003_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00004_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00004_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00006_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00006_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00007_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00007_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00008_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00009_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00009_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00010_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00010_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00011_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00011_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00012_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00014_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00014_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00015_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00015_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00018_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00019_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00019_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00020_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00020_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00021_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00021_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00022_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00023_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00023_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00024_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00026_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00026_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00027_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00028_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00029_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00029_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00030_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00031_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00032_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00032_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00035_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00037_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00037_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00039_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00040_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00040_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00041_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00043_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00043_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00044_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00044_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00045_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00045_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00046_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00046_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00047_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00047_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00048_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00048_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00049_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00049_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00050_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00050_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00051_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00051_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00052_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00052_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00053_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00053_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00055_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00055_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00056_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00057_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00057_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00060_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00060_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00061_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00062_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00062_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00064_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00065_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00065_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00066_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00066_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00067_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00068_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00068_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00069_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00070_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00070_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00071_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00071_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00072_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00074_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00074_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00076_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00076_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00079_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00079_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00081_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00084_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00084_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00085_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00086_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00086_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00087_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00087_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00088_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00088_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00089_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00089_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00090_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00090_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00091_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00091_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00093_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00093_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00095_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00095_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00096_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00097_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00097_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00098_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00098_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00099_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00099_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00100_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00100_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00101_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00101_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00102_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00104_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00104_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00105_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00105_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00107_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00107_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00108_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00109_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00110_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00110_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00111_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00111_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00112_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00113_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00113_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00115_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00115_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00116_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00119_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00120_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00123_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00123_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00124_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00124_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00129_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00129_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00130_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00131_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00131_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00132_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00132_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00133_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00136_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00136_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00137_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00137_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00138_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00138_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00139_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00140_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00142_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00142_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00143_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00143_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00144_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00144_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00145_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00145_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00147_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00147_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00148_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00148_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00149_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00149_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00150_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00151_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00152_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00152_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00154_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00154_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00155_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00155_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00156_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00156_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00157_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00157_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00158_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00158_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00160_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00160_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00161_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00161_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00162_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00162_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00163_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00163_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00164_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00164_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00165_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00165_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00166_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00166_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00167_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00167_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00168_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00168_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00170_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00171_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00171_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00173_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00173_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00174_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00174_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00176_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00176_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00177_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00177_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00179_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00180_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00180_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00183_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00185_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00186_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00186_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00187_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00187_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00188_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00188_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00189_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00189_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00190_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00190_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00191_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00191_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00192_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00192_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00193_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00194_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00195_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00195_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00196_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00196_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00198_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00198_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00199_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00199_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00200_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00200_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00201_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00201_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00202_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00202_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00203_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00203_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00204_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00204_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00205_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00205_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00206_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00206_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00207_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00208_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00208_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00210_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00210_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00211_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00212_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00212_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00213_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00213_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00216_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00216_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00220_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00220_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00221_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00221_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00222_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00222_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00223_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00223_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00225_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00225_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00226_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00226_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00228_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00228_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00230_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00231_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00232_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00232_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00235_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00236_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00237_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00237_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00238_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00238_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00239_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00239_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00240_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00241_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00241_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00242_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00244_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00244_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00245_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00245_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00246_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00246_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00247_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00248_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00248_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00249_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00249_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00250_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00250_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00253_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00254_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00254_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00255_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00255_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00256_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00256_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00257_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00257_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00258_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00259_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00260_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00262_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00263_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00263_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00264_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00264_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00265_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00265_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00266_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00266_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00267_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00268_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00269_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00269_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00270_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00273_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00273_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00275_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00275_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00276_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00276_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00277_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00277_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00278_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00279_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00281_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00281_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00282_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00283_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00284_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00284_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00285_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00286_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00288_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00288_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00290_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00291_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00292_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00292_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00293_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00293_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00295_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00296_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00297_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00298_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00299_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00300_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00300_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00301_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00301_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00302_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00303_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00303_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00304_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00305_ses-01_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00306_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00307_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00308_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00309_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00310_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00312_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00313_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00314_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00315_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00316_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00318_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00322_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00323_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00324_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00325_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00326_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00327_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00328_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00329_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00330_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00332_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00333_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00334_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00335_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00336_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00337_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00338_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00339_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00341_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00343_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00344_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00345_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00346_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00347_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00348_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00349_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00350_ses-02_T1w.nii,1'
                                                   'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output\sub-00351_ses-02_T1w.nii,1'
                                                   };
%%
matlabbatch{1}.spm.spatial.preproc.channel.biasreg = 0.001;
matlabbatch{1}.spm.spatial.preproc.channel.biasfwhm = 60;
matlabbatch{1}.spm.spatial.preproc.channel.write = [1 1];
matlabbatch{1}.spm.spatial.preproc.tissue(1).tpm = {'C:\Users\NICT_WS\Documents\MATLAB\toolbox\spm12\tpm\TPM.nii,1'};
matlabbatch{1}.spm.spatial.preproc.tissue(1).ngaus = 1;
matlabbatch{1}.spm.spatial.preproc.tissue(1).native = [1 1];
matlabbatch{1}.spm.spatial.preproc.tissue(1).warped = [0 0];
matlabbatch{1}.spm.spatial.preproc.tissue(2).tpm = {'C:\Users\NICT_WS\Documents\MATLAB\toolbox\spm12\tpm\TPM.nii,2'};
matlabbatch{1}.spm.spatial.preproc.tissue(2).ngaus = 1;
matlabbatch{1}.spm.spatial.preproc.tissue(2).native = [1 1];
matlabbatch{1}.spm.spatial.preproc.tissue(2).warped = [0 0];
matlabbatch{1}.spm.spatial.preproc.tissue(3).tpm = {'C:\Users\NICT_WS\Documents\MATLAB\toolbox\spm12\tpm\TPM.nii,3'};
matlabbatch{1}.spm.spatial.preproc.tissue(3).ngaus = 2;
matlabbatch{1}.spm.spatial.preproc.tissue(3).native = [1 0];
matlabbatch{1}.spm.spatial.preproc.tissue(3).warped = [0 0];
matlabbatch{1}.spm.spatial.preproc.tissue(4).tpm = {'C:\Users\NICT_WS\Documents\MATLAB\toolbox\spm12\tpm\TPM.nii,4'};
matlabbatch{1}.spm.spatial.preproc.tissue(4).ngaus = 3;
matlabbatch{1}.spm.spatial.preproc.tissue(4).native = [1 0];
matlabbatch{1}.spm.spatial.preproc.tissue(4).warped = [0 0];
matlabbatch{1}.spm.spatial.preproc.tissue(5).tpm = {'C:\Users\NICT_WS\Documents\MATLAB\toolbox\spm12\tpm\TPM.nii,5'};
matlabbatch{1}.spm.spatial.preproc.tissue(5).ngaus = 4;
matlabbatch{1}.spm.spatial.preproc.tissue(5).native = [1 0];
matlabbatch{1}.spm.spatial.preproc.tissue(5).warped = [0 0];
matlabbatch{1}.spm.spatial.preproc.tissue(6).tpm = {'C:\Users\NICT_WS\Documents\MATLAB\toolbox\spm12\tpm\TPM.nii,6'};
matlabbatch{1}.spm.spatial.preproc.tissue(6).ngaus = 2;
matlabbatch{1}.spm.spatial.preproc.tissue(6).native = [0 0];
matlabbatch{1}.spm.spatial.preproc.tissue(6).warped = [0 0];
matlabbatch{1}.spm.spatial.preproc.warp.mrf = 1;
matlabbatch{1}.spm.spatial.preproc.warp.cleanup = 1;
matlabbatch{1}.spm.spatial.preproc.warp.reg = [0 0.001 0.5 0.05 0.2];
matlabbatch{1}.spm.spatial.preproc.warp.affreg = 'mni';
matlabbatch{1}.spm.spatial.preproc.warp.fwhm = 0;
matlabbatch{1}.spm.spatial.preproc.warp.samp = 3;
matlabbatch{1}.spm.spatial.preproc.warp.write = [0 0];
matlabbatch{2}.spm.tools.dartel.warp.images{1}(1) = cfg_dep('Segment: rc1 Images', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','tiss', '()',{1}, '.','rc', '()',{':'}));
matlabbatch{2}.spm.tools.dartel.warp.images{2}(1) = cfg_dep('Segment: rc2 Images', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','tiss', '()',{2}, '.','rc', '()',{':'}));
matlabbatch{2}.spm.tools.dartel.warp.settings.template = 'Template';
matlabbatch{2}.spm.tools.dartel.warp.settings.rform = 0;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(1).its = 3;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(1).rparam = [4 2 1e-06];
matlabbatch{2}.spm.tools.dartel.warp.settings.param(1).K = 0;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(1).slam = 16;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(2).its = 3;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(2).rparam = [2 1 1e-06];
matlabbatch{2}.spm.tools.dartel.warp.settings.param(2).K = 0;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(2).slam = 8;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(3).its = 3;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(3).rparam = [1 0.5 1e-06];
matlabbatch{2}.spm.tools.dartel.warp.settings.param(3).K = 1;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(3).slam = 4;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(4).its = 3;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(4).rparam = [0.5 0.25 1e-06];
matlabbatch{2}.spm.tools.dartel.warp.settings.param(4).K = 2;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(4).slam = 2;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(5).its = 3;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(5).rparam = [0.25 0.125 1e-06];
matlabbatch{2}.spm.tools.dartel.warp.settings.param(5).K = 4;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(5).slam = 1;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(6).its = 3;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(6).rparam = [0.25 0.125 1e-06];
matlabbatch{2}.spm.tools.dartel.warp.settings.param(6).K = 6;
matlabbatch{2}.spm.tools.dartel.warp.settings.param(6).slam = 0.5;
matlabbatch{2}.spm.tools.dartel.warp.settings.optim.lmreg = 0.01;
matlabbatch{2}.spm.tools.dartel.warp.settings.optim.cyc = 3;
matlabbatch{2}.spm.tools.dartel.warp.settings.optim.its = 3;
matlabbatch{3}.spm.tools.dartel.mni_norm.template(1) = cfg_dep('Run Dartel (create Templates): Template (Iteration 6)', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','template', '()',{7}));
matlabbatch{3}.spm.tools.dartel.mni_norm.data.subjs.flowfields(1) = cfg_dep('Run Dartel (create Templates): Flow Fields', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files', '()',{':'}));
matlabbatch{3}.spm.tools.dartel.mni_norm.data.subjs.images{1}(1) = cfg_dep('Segment: c1 Images', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','tiss', '()',{1}, '.','c', '()',{':'}));
matlabbatch{3}.spm.tools.dartel.mni_norm.vox = [NaN NaN NaN];
matlabbatch{3}.spm.tools.dartel.mni_norm.bb = [NaN NaN NaN
                                               NaN NaN NaN];
matlabbatch{3}.spm.tools.dartel.mni_norm.preserve = 1;
matlabbatch{3}.spm.tools.dartel.mni_norm.fwhm = [8 8 8];
matlabbatch{4}.spm.tools.masking{1}.makeavg.innames(1) = cfg_dep('Normalise to MNI Space: MNI Smo. Warped - Amount (Image 1)', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('()',{':', 1}));
matlabbatch{4}.spm.tools.masking{1}.makeavg.avgexpr = 'mean(X)';
matlabbatch{4}.spm.tools.masking{1}.makeavg.outname = 'average.nii';
matlabbatch{4}.spm.tools.masking{1}.makeavg.outdir = {'D:\MRI\pnTTC\c1c2_struc\spm\02_spm\output'};
matlabbatch{5}.spm.tools.masking{1}.optthr.inname = '<UNDEFINED>';
matlabbatch{5}.spm.tools.masking{1}.optthr.optfunc = '@opt_thr_corr';
matlabbatch{5}.spm.tools.masking{1}.optthr.outname = 'average_optthr.nii';
matlabbatch{5}.spm.tools.masking{1}.optthr.outdir = {''};
matlabbatch{6}.spm.util.tvol.matfiles(1) = cfg_dep('Segment: Seg Params', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','param', '()',{':'}));
matlabbatch{6}.spm.util.tvol.tmax = 3;
matlabbatch{6}.spm.util.tvol.mask = {'C:\Users\NICT_WS\Documents\MATLAB\toolbox\spm12\tpm\mask_ICV.nii,1'};
matlabbatch{6}.spm.util.tvol.outf = 'tissue_volumes.csv';
